# Generated by Django 5.0.4 on 2024-06-23 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desktop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storelist',
            options={'managed': True},
        ),
    ]
