# Generated by Django 5.0.4 on 2024-06-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desktop', '0002_alter_storelist_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='storelist',
            name='mt_number',
            field=models.CharField(default='00', max_length=32),
        ),
        migrations.AddField(
            model_name='storelist',
            name='mt_password',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='storelist',
            name='mt_user',
            field=models.CharField(default='00', max_length=32),
        ),
    ]
