# Generated by Django 5.0.4 on 2024-06-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desktop', '0003_storelist_mt_number_storelist_mt_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storelist',
            name='mt_password',
            field=models.TextField(default='12345678'),
        ),
    ]
