# Generated by Django 5.0.4 on 2024-06-26 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desktop', '0004_alter_storelist_mt_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodslist',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='orderform',
            options={'managed': True},
        ),
    ]
