# Generated by Django 5.0.4 on 2024-06-26 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desktop', '0006_goodslist_category_id_goodslist_sku_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderform',
            old_name='store_id',
            new_name='store',
        ),
    ]
