# Generated by Django 5.0.4 on 2024-06-26 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desktop', '0007_rename_store_id_orderform_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderform',
            old_name='store',
            new_name='store_id',
        ),
    ]
